name: Daily AI News Scraper

on:
  schedule:
    # Run daily at 8:00 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape_ai_news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create config directory and .env file
      run: |
        mkdir -p config
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" > config/.env
    
    - name: Run AI News Scraper
      run: |
        python app/scraper.py
    
    - name: Log scraper completion
      run: |
        echo "AI News Scraper completed at $(date)" 