name: Daily AI News Scraper

on:
  schedule:
    # Run daily at 8:00 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape_ai_news:
    runs-on: ubuntu-latest
    environment: Neon
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Verify DATABASE_URL is set
      run: |
        if [ -z "${{ secrets.DATABASE_URL }}" ]; then
          echo "❌ DATABASE_URL secret is not set!"
          echo "💡 Please check DATABASE_URL in your 'Neon' environment variables"
          exit 1
        else
          echo "✅ DATABASE_URL is configured in Neon environment"
        fi
    
    - name: Test Database Connection
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        echo "🔐 Testing database connection..."
        python -c "from app.database import NewsDatabase; db = NewsDatabase(); print('✅ Database connection successful')"
    
    - name: Run AI News Scraper
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        echo "🚀 Starting AI News Scraper..."
        python app/scraper.py
        echo "✅ Scraper completed successfully!"
    
    - name: Log completion
      run: |
        echo "🎉 AI News Scraper workflow completed at $(date)" 